# Build every Centennial Conference 2025 game (any game involving a
# Centennial team: conference, non-conference, playoff and bowl games).
#
#   Rscript analysis/build_centennial_2025.R
#
# Network use is limited to what this scope needs, and every page is cached
# in data-raw/cache/ (throttled 3 s apart by fetch_html()), so a rerun makes
# no requests:
#   - the CC 2025 standings page (members),
#   - each Centennial team's and each opponent's team page (2025 conference
#     + "*" conference markers), plus one standings page per opponent
#     conference (its name),
#   - each game's plays page.
# The season index comes from data-raw/index/2025.csv.

devtools::load_all(quiet = TRUE)
# OFFLINE=1 builds only from data-raw/cache/ (no requests); uncached pages are
# reported as pending. Rerun without it to fetch them.
if (nzchar(Sys.getenv("OFFLINE"))) options(d3ballR.offline = TRUE)
season <- 2025
code <- "CC"

members <- conference_members(season, code)$team
idx <- build_season_index(season)
games <- index_games_for_teams(idx, members)
opponents <- setdiff(unique(c(games$home, games$away)), members)
message(length(members), " ", code, " teams, ", length(opponents), " opponents, ", nrow(games), " games")

conf <- build_conference_table(season, c(members, opponents))
pending_teams <- setdiff(c(members, opponents), conf$table$team)
urls <- games$boxscore_url[!is.na(games$boxscore_url)]
built <- build_all_pbp(urls)

# ---- reports ----------------------------------------------------------------
md_table <- function(df) {
  df[] <- lapply(df, function(x) ifelse(is.na(x), "", as.character(x)))
  c(paste0("| ", paste(names(df), collapse = " | "), " |"),
    paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|"),
    apply(df, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |")))
}

# conference cross-check: d3's "*" marker vs shared membership
cc <- do.call(rbind, lapply(built, function(g) data.frame(
  game_id = g$game_id[1], game_date = g$game_date[1], season_type = g$season_type[1],
  away = g$away[1], home = g$home[1],
  away_team_conference = g$away_team_conference[1], home_team_conference = g$home_team_conference[1],
  conference_game = g$conference_game[1], shared_conference = attr(g, "shared_conference"))))
cc$agree <- cc$conference_game %in% cc$shared_conference & !is.na(cc$conference_game)
utils::write.csv(cc, "analysis/checks/conference_check.csv", row.names = FALSE, na = "")

rec <- utils::read.csv("analysis/checks/score_reconciliation.csv", na.strings = "")
fail <- utils::read.csv("analysis/checks/build_failures.csv", na.strings = "")

out <- c(
  paste0("# Centennial ", season, " build report"), "",
  "Generated by `analysis/build_centennial_2025.R`.", "",
  "## Scope", "",
  paste0("- **Centennial teams (", length(members), "):** ", paste(members, collapse = ", "), "."),
  paste0("- **Games:** ", nrow(games), " in the ", season, " index involving a Centennial team (",
         sum(games$season_type == "postseason"), " postseason)."),
  paste0("- **Built:** ", length(built), "; not built: ", nrow(fail), "."),
  if (length(pending_teams)) paste0("- **Team pages not yet fetched (", length(pending_teams), "; conference NA until fetched):** ",
                                    paste(sort(pending_teams), collapse = ", "), ".") else NULL,
  paste0("- **Team-to-conference table** (`data-raw/conferences/", season, ".csv`): ",
         nrow(conf$table), " teams (the Centennial teams + every opponent), across ",
         length(unique(stats::na.omit(conf$table$conference))), " conferences; ",
         sum(is.na(conf$table$conference_code)), " with no ", season, " conference (independent or non-D3)."),
  "",
  "## Score reconciliation", "",
  "For each game, points by team from `score_pts` (positive -> `pos_team`, negative -> `def_pos_team`) vs the boxscore line-score final.", "",
  paste0("**", sum(rec$score_reconciled), " of ", nrow(rec), " games pass.**"), "",
  md_table(transform(rec, result = ifelse(score_reconciled, "PASS", "FAIL"))[
    , c("game_id", "game_date", "away", "away_final", "away_pts_parsed", "home", "home_final", "home_pts_parsed", "result")]),
  "",
  "## Conference game: d3's \"*\" marker vs shared membership", "",
  "`conference_game` comes from d3's schedule marker. `shared_conference` = both teams in the same conference that season.", "",
  paste0(sum(cc$agree), " of ", nrow(cc), " games agree. Disagreements:"), "",
  if (any(!cc$agree)) md_table(cc[!cc$agree, c("game_id", "game_date", "season_type", "away", "away_team_conference",
                                              "home", "home_team_conference", "conference_game", "shared_conference")]) else "None.",
  ""
)
if (nrow(fail)) out <- c(out, "## Games not built", "",
                         "Rerun `Rscript analysis/build_centennial_2025.R` (without OFFLINE) to fetch and build them; cached pages are reused.", "",
                         md_table(fail), "")
writeLines(out, paste0("analysis/checks/centennial_", season, ".md"))
cat(out, sep = "\n")
