# Season-index validation report.
#
# Writes analysis/checks/season_index_{season}.md from the cached season
# index and the built per-game CSVs. No network: it reads
# data-raw/index/{season}.csv and analysis/pbp/. Change the parameters to
# validate another season / team.
#
#   Rscript analysis/season_index_report.R

devtools::load_all(quiet = TRUE)

season <- 2025
team <- "Carnegie Mellon"          # scoreboard spelling
bowl_game_id <- "20251122_xsab"     # a known non-NCAA postseason game
td_check <- list(game_id = "20251122_xsab", period = 3, clock_end = "12:23")
expected_games <- c(1200, 1300)

idx <- build_season_index(season)   # cached
sd <- read_season_dates()
out <- character()
add <- function(...) out <<- c(out, paste0(...))
md_table <- function(df) {
  df[] <- lapply(df, function(x) ifelse(is.na(x), "", as.character(x)))
  c(paste0("| ", paste(names(df), collapse = " | "), " |"),
    paste0("|", paste(rep("---", ncol(df)), collapse = "|"), "|"),
    apply(df, 1, function(r) paste0("| ", paste(r, collapse = " | "), " |")))
}

add("# Season index validation: ", season)
add("")
add("Generated by `analysis/season_index_report.R` from `data-raw/index/", season,
    ".csv` (built by `build_season_index(", season, ")`) and `analysis/pbp/`.")
add("")

# 1. week numbering -----------------------------------------------------------
add("## How d3football numbers weeks")
add("")
add("- **Week pages:** the composite scoreboard has one page per week, `https://www.d3football.com/scoreboard/{season}/composite?view=N`, ",
    "with N = 1, 2, 3, ... in calendar order. `view=1` is the week of the first Saturday in September ",
    "(Sep 6, 2025; also Sep 7 in both 2019 and 2024). A view also holds that week's Thursday / Friday games, ",
    "and sometimes a Sunday game (2024 view 1 has a Sunday, Sep 8, game).")
add("- **No round labels:** postseason weeks continue the same numbering. There are no round or bowl labels anywhere: ",
    "NCAA playoff games and bowl games (e.g. the Centennial-MAC Bowl Series) sit together in one ",
    "Date / Away / Home / Status / Links table. A row with an empty date is a neutral-site note (\"@ Canton, Ohio\") for the game above it.")
add("- **End of the season:** pages past the last week come back empty (", season, ": view 17), so `build_season_index()` stops after two empty views. ",
    "Only some seasons' pages link all their week views (2025 does; 2024 and 2019 link only view 1), so the indexer steps through views rather than reading the links.")
add("- **Our week numbers:** postseason is decided by date, not by d3's label (there is none): `season_type = \"postseason\"` when ",
    "`game_date > regular_season_end` from `data-raw/season_dates.csv`. Regular-season `week` = view number. ",
    "Postseason weeks restart at 1 (cfbfastR): `week = view - first postseason view + 1`.")
add("")
wk <- do.call(rbind, lapply(split(idx, idx$scoreboard_view), function(d) data.frame(
  view = d$scoreboard_view[1], dates = paste(min(d$game_date), "to", max(d$game_date)),
  games = nrow(d), season_type = paste(unique(d$season_type), collapse = "/"),
  week = paste(unique(d$week), collapse = "/"))))
out <- c(out, md_table(wk[order(wk$view), ]))
add("")
add("Regular season end for ", season, ": ", format(sd$regular_season_end[sd$season == season]), ".")
add("")

# 2. team games ---------------------------------------------------------------
tg <- index_team_games(idx, team)
add("## All ", team, " games in the index")
add("")
csv <- list.files("analysis/pbp", pattern = "csv$", full.names = TRUE)
built <- sub("\\.csv$", "", basename(csv))
tg$built <- ifelse(tg$game_id %in% built, "yes", "no")
out <- c(out, md_table(tg[, c("game_id", "game_date", "week", "season_type", "away", "home", "built")]))
add("")
add(nrow(tg), " games found; ", sum(tg$game_id %in% built), " of ", length(built),
    " built per-game CSVs are in the index",
    if (all(built %in% idx$game_id)) " (all found)." else paste0(". MISSING: ", paste(setdiff(built, idx$game_id), collapse = ", ")))
add("")

# 3. bowl game ------------------------------------------------------------------
b <- idx[idx$game_id %in% bowl_game_id, ]
add("## ", bowl_game_id, " (", b$away, " at ", b$home, ", ", b$game_date, ")")
add("")
add("- **Our label:** `season_type = \"", b$season_type, "\"`, `week = ", b$week, "` (scoreboard view ", b$scoreboard_view,
    "; ", b$game_date, " > regular_season_end ", format(sd$regular_season_end[sd$season == season]), "). ",
    if (b$season_type == "postseason") "Correctly postseason." else "**NOT postseason. Check.**")
add("- **How d3 labels it:** it doesn't. On the week ", b$scoreboard_view, " scoreboard it is an ordinary row (\"",
    b$date_text, " | ", b$away, " ", b$away_score, " | ", b$home, " ", b$home_score, " | ", b$status, "\"), ",
    "next to the NCAA first-round games, with no round, bowl or \"Centennial-MAC Bowl Series\" text. ",
    "The CMU team page lists it as \"11/22 vs. Misericordia W, 24-17\". The boxscore header reads ",
    "\"Misericordia at Carnegie Mellon - Pittsburgh, Pa. 11/22/2025 - 12:00 PM\". In the play-by-play page, the ",
    "words \"Bowl\" / \"Playoff\" appear only in the site navigation menu (checked 2026-10-02). So `season_type` ",
    "can't tell a bowl from an NCAA playoff game; both are \"postseason\".")
add("")

# 4. TD check ------------------------------------------------------------------
g <- utils::read.csv(file.path("analysis/pbp", paste0(td_check$game_id, ".csv")), na.strings = "")
r <- g[g$period == td_check$period & g$clock_end %in% td_check$clock_end & g$touchdown, ]
add("## Fumble-recovery TD check (", td_check$game_id, ", Q", td_check$period, " ", td_check$clock_end, ")")
add("")
out <- c(out, md_table(r[, c("play_index", "period", "clock_end", "pos_team", "def_pos_team",
                             "touchdown", "turnover", "fumble_vec", "score_pts", "play_text")]))
add("")
ok <- nrow(r) == 1 && r$touchdown && r$turnover && r$score_pts < 0
add(if (ok) "PASS: " else "FAIL: ", "touchdown = ", r$touchdown, ", turnover = ", r$turnover,
    ", score_pts = ", r$score_pts, " from ", r$pos_team, "'s view. The defense (", r$def_pos_team,
    ") scored on the offense's fumble.")
add("")

# 5. game count ---------------------------------------------------------------
n <- nrow(idx)
add("## Total games in the ", season, " index")
add("")
add("- **Total:** ", n, " games (", sum(!is.na(idx$game_id)), " with a d3 boxscore, ", sum(is.na(idx$game_id)),
    " without; ", sum(idx$status == "Cancelled"), " of those are cancelled).")
add("- **Split:** ", sum(idx$season_type == "regular"), " regular season, ", sum(idx$season_type == "postseason"), " postseason.")
teams <- unique(c(idx$home, idx$away))
add("- **Teams:** ", length(teams), " distinct names (including non-D3 opponents).")
add("- **Expected:** ", expected_games[1], "-", expected_games[2], ". ",
    if (n >= expected_games[1] && n <= expected_games[2]) "Within range." else "**OUT OF RANGE. Investigate.**")
add("")

# 6. week disagreement -------------------------------------------------------
st <- idx$season_type
dw <- date_based_week(as.Date(idx$game_date), idx$season, st, sd)
dis <- idx[dw != idx$week, ]
dis$date_based_week <- dw[dw != idx$week]
dis$weekday <- weekdays(as.Date(dis$game_date))
add("## Scoreboard week vs date-based (Sunday-to-Saturday) week")
add("")
add("Date-based week: regular-season week 1 is the Sunday-to-Saturday week of the first Saturday in September; ",
    "postseason week 1 is the week of the first Saturday after `regular_season_end`. This is also the fallback ",
    "`build_pbp()` uses for a game missing from the index.")
add("")
if (nrow(dis)) {
  add(nrow(dis), " disagreement(s):")
  add("")
  out <- c(out, md_table(dis[, c("game_id", "game_date", "weekday", "scoreboard_view", "week", "date_based_week", "away", "home")]))
} else {
  add("None. All ", n, " games agree.")
}
add("")

writeLines(out, file.path("analysis/checks", paste0("season_index_", season, ".md")))
cat(out, sep = "\n")
